image: node:alpine

stages:
- build
- test

Build:
  stage: build
  script:
    - npm install -g yarn
    - apk add --no-cache git
Test:
  stage: test
  before_script:
    - yarn
  script:
    - yarn test
