name: Cypress Tests

on:
  push:
    branches: [ newdxp ]
  pull_request:
    branches: [ newdxp ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.18.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Start development server
        run: |
          # Start server
          yarn start
        env:
          CI: true

      - name: Wait for server to be ready
        run: |
          # Wait up to 60 seconds for server to start
          timeout=60
          while [ $timeout -gt 0 ]; do
            if curl -f http://localhost:3000 > /dev/null 2>&1; then
              echo "Server is ready!"
              break
            fi
            echo "Waiting for server... ($timeout seconds remaining)"
            sleep 2
            timeout=$((timeout-2))
          done

          if [ $timeout -le 0 ]; then
            echo "Server failed to start within 60 seconds"
            echo "=== Server log ==="
            cat server.log || echo "No server log found"
            exit 1
          fi

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false  # Dependencies already installed
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          browser: chrome
          record: false
        env:
          # Ensure Cypress runs with the same Node options if needed
          NODE_OPTIONS: "--openssl-legacy-provider"

      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7

      - name: Upload server logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs
          path: server.log
          retention-days: 7